// UniverCert · Landing data (features + comparison) — i18n inline pra simplicidade

import type { Locale } from '@/lib/i18n';

type ML = Partial<Record<Locale, string>> & { pt: string };

export type Feature = { icon: string; title: ML; desc: ML; cat: string; highlight?: boolean };

// 50+ features divididas em 8 categorias
export const FEATURES: Feature[] = [
  // EDITOR
  { cat: 'editor', icon: '🎨', title: { pt: 'Editor drag-and-drop', en: 'Drag-and-drop editor', es: 'Editor drag-and-drop', fr: 'Éditeur drag-and-drop' }, desc: { pt: 'Posicione textos, QR, logos e fotos com mouse. Multi-select, marquee, align/distribute.', en: 'Position text, QR, logos with mouse. Multi-select, marquee, align/distribute.', es: 'Posiciona textos, QR, logos con mouse. Multi-select, marquee, align/distribute.', fr: 'Positionnez textes, QR, logos avec la souris. Multi-select, marquee, alignement.' } },
  { cat: 'editor', icon: '📐', title: { pt: 'Auto-fit text', en: 'Auto-fit text', es: 'Auto-fit text', fr: 'Auto-fit text' }, desc: { pt: 'Texto reescala automaticamente quando você redimensiona a caixa.', en: 'Text auto-rescales when you resize the box.', es: 'El texto se reescala al redimensionar.', fr: 'Le texte se redimensionne automatiquement.' } },
  { cat: 'editor', icon: '📄', title: { pt: 'Importe PDF/Figma/Canva', en: 'Import PDF/Figma/Canva', es: 'Importa PDF/Figma/Canva', fr: 'Import PDF/Figma/Canva' }, desc: { pt: 'Suba qualquer design existente. PDF interativo via pdf.js, PNG, JPG, SVG.', en: 'Upload any existing design. Interactive PDF via pdf.js, PNG, JPG, SVG.', es: 'Sube cualquier diseño. PDF interactivo, PNG, JPG, SVG.', fr: 'Importez n\'importe quel design. PDF interactif, PNG, JPG, SVG.' } },
  { cat: 'editor', icon: '📏', title: { pt: 'A4/Letter/A3/Square/Custom', en: 'A4/Letter/A3/Square/Custom', es: 'A4/Letter/A3/Square/Custom', fr: 'A4/Letter/A3/Square/Custom' }, desc: { pt: 'Page sizes profissionais + dimensão personalizada.', en: 'Pro page sizes + custom dimensions.', es: 'Tamaños de página pro + personalizado.', fr: 'Tailles pro + dimensions personnalisées.' } },
  { cat: 'editor', icon: '🔄', title: { pt: 'Undo/redo + 15 atalhos', en: 'Undo/redo + 15 shortcuts', es: 'Undo/redo + 15 atajos', fr: 'Undo/redo + 15 raccourcis' }, desc: { pt: 'Cmd+Z, Cmd+D, arrows, Delete, Escape — tudo que você espera de Figma.', en: 'Cmd+Z, Cmd+D, arrows, Delete — everything you expect from Figma.', es: 'Cmd+Z, Cmd+D, arrows, Delete — todo lo de Figma.', fr: 'Cmd+Z, Cmd+D, flèches, Delete — tout ce qu\'on attend.' } },
  { cat: 'editor', icon: '🖼', title: { pt: 'Biblioteca de assets R2', en: 'Asset library R2', es: 'Biblioteca de assets R2', fr: 'Bibliothèque assets R2' }, desc: { pt: 'Reutilize fundos, logos, assinaturas. Hosted no Cloudflare R2 (zero egress fee).', en: 'Reuse backgrounds, logos, signatures. Cloudflare R2 (zero egress fee).', es: 'Reutiliza fondos, logos, firmas. Cloudflare R2 sin egress fee.', fr: 'Réutilisez fonds, logos, signatures. Cloudflare R2 sans egress.' } },
  { cat: 'editor', icon: '👁', title: { pt: 'Preview real-time', en: 'Real-time preview', es: 'Preview real-time', fr: 'Aperçu temps réel' }, desc: { pt: 'Veja o cert renderizado em tempo real conforme edita.', en: 'See cert rendered in real-time as you edit.', es: 'Ver cert renderizado en tiempo real.', fr: 'Voir le cert rendu en temps réel.' } },

  // AI
  { cat: 'ai', icon: '🤖', title: { pt: 'Gerar template com IA', en: 'AI template generator', es: 'Generar template con IA', fr: 'Générer template avec IA' }, desc: { pt: 'Descreva o curso, Claude Haiku gera layoutJson completo em segundos.', en: 'Describe the course, Claude Haiku generates complete layout in seconds.', es: 'Describe el curso, Claude genera layout completo.', fr: 'Décrivez le cours, Claude génère un layout complet.' } },
  { cat: 'ai', icon: '🆔', title: { pt: 'OCR de RG/CNH', en: 'RG/CNH/ID OCR', es: 'OCR de ID/cédula', fr: 'OCR pièce d\'identité' }, desc: { pt: 'Tire foto do documento, IA extrai nome + CPF + data de nasc automaticamente.', en: 'Photo of ID, AI extracts name + ID number + DOB.', es: 'Foto del ID, IA extrae nombre + cédula + nacimiento.', fr: 'Photo de la pièce, IA extrait nom + numéro + naissance.' } },
  { cat: 'ai', icon: '🔍', title: { pt: 'Validação de foto IA', en: 'AI photo validation', es: 'Validación de foto IA', fr: 'Validation photo IA' }, desc: { pt: 'Detecta IA-generated, photoshop, blur, recorte ruim. Score 0-100.', en: 'Detects AI-generated, photoshop, blur, bad crop. Score 0-100.', es: 'Detecta foto IA, photoshop, blur. Score 0-100.', fr: 'Détecte photo IA, photoshop, flou. Score 0-100.' } },
  { cat: 'ai', icon: '👥', title: { pt: 'Face match anti-fraude', en: 'Face match anti-fraud', es: 'Face match anti-fraude', fr: 'Face match anti-fraude' }, desc: { pt: 'Compara selfie com RG/cert antigo. Claude Sonnet vision verifica autenticidade.', en: 'Compares selfie with ID/old cert. Claude Sonnet vision verifies authenticity.', es: 'Compara selfie con ID/cert antiguo. Claude Sonnet vision.', fr: 'Compare selfie avec pièce/cert. Claude Sonnet vision.' } },
  { cat: 'ai', icon: '💡', title: { pt: 'Suggest improvements', en: 'Suggest improvements', es: 'Sugerir mejoras', fr: 'Suggestions IA' }, desc: { pt: 'IA critica seu template e sugere melhorias por categoria (typography, spacing, hierarchy).', en: 'AI critiques template & suggests improvements by category.', es: 'IA critica template y sugiere mejoras.', fr: 'IA critique et suggère des améliorations.' } },

  // DELIVERY
  { cat: 'delivery', icon: '📧', title: { pt: 'Email via Resend', en: 'Email via Resend', es: 'Email via Resend', fr: 'Email via Resend' }, desc: { pt: 'Envio transacional com DKIM/SPF + custom domain (escola.com).', en: 'Transactional with DKIM/SPF + custom domain.', es: 'Transaccional con DKIM/SPF + dominio custom.', fr: 'Transactionnel DKIM/SPF + domaine custom.' } },
  { cat: 'delivery', icon: '💬', title: { pt: 'WhatsApp Business API', en: 'WhatsApp Business API', es: 'WhatsApp Business API', fr: 'WhatsApp Business API' }, desc: { pt: 'Envia link do cert via WhatsApp oficial (Meta). Templates HSM aprovados.', en: 'Sends cert link via official WhatsApp (Meta). Approved HSM templates.', es: 'Envía link vía WhatsApp oficial (Meta).', fr: 'Envoie le lien via WhatsApp officiel (Meta).' } },
  { cat: 'delivery', icon: '🔗', title: { pt: 'LinkedIn "Add to Profile"', en: 'LinkedIn "Add to Profile"', es: 'LinkedIn "Add to Profile"', fr: 'LinkedIn "Add to Profile"' }, desc: { pt: 'Botão oficial LinkedIn que adiciona cert direto no perfil do aluno.', en: 'Official LinkedIn button adds cert directly to user profile.', es: 'Botón oficial LinkedIn agrega cert al perfil.', fr: 'Bouton officiel LinkedIn ajoute au profil.' } },
  { cat: 'delivery', icon: '🍎', title: { pt: 'Apple Wallet pkpass', en: 'Apple Wallet pkpass', es: 'Apple Wallet pkpass', fr: 'Apple Wallet pkpass' }, desc: { pt: 'Cert vai pra carteira do iPhone. PKCS#7 signed real.', en: 'Cert in iPhone wallet. PKCS#7 signed real.', es: 'Cert en wallet iPhone. PKCS#7 firmado real.', fr: 'Cert dans Apple Wallet. PKCS#7 signé.' } },
  { cat: 'delivery', icon: '📱', title: { pt: 'Google Wallet JWT', en: 'Google Wallet JWT', es: 'Google Wallet JWT', fr: 'Google Wallet JWT' }, desc: { pt: 'Save to Google Wallet com JWT RS256 assinado em edge runtime.', en: 'Save to Google Wallet with JWT RS256 signed at edge.', es: 'Save to Google Wallet con JWT RS256.', fr: 'Save to Google Wallet avec JWT RS256.' } },
  { cat: 'delivery', icon: '📤', title: { pt: 'Share bar mobile-first', en: 'Mobile-first share bar', es: 'Share bar mobile-first', fr: 'Barre de partage mobile' }, desc: { pt: '9 canais: LinkedIn, WhatsApp, X, FB, Email, Wallets, native share, copy link.', en: '9 channels: LinkedIn, WhatsApp, X, FB, Email, Wallets, native, copy.', es: '9 canales de share incluyendo wallets.', fr: '9 canaux de partage avec wallets.' } },
  { cat: 'delivery', icon: '📨', title: { pt: 'Workflows de email/WA', en: 'Email/WA workflows', es: 'Workflows email/WA', fr: 'Workflows email/WA' }, desc: { pt: 'Triggers: cert.issued, request.submitted, needs_revision. Customizável.', en: 'Triggers: cert.issued, request.submitted, needs_revision. Customizable.', es: 'Triggers personalizables: cert.issued, etc.', fr: 'Triggers personnalisables: cert.issued, etc.' } },

  // INTEGRATIONS
  { cat: 'integrations', icon: '⚡', title: { pt: '2 modos: automático ou aprovação', en: '2 modes: auto or approval-gated', es: '2 modos: automático o por aprobación', fr: '2 modes : auto ou validation' }, desc: { pt: 'Auto-emite via webhook (Hotmart/Kiwify/Memberkit/Fluent) ao concluir, ou exige prova de conhecimento — foto, redação, quiz, documento — antes do aprovador liberar.', en: 'Auto-issue on course completion (Hotmart, Kiwify, Memberkit, Fluent, Zapier), or require proof of knowledge — photo, essay, quiz, document — before reviewer approves.', es: 'Emite solo al completar (Hotmart, Kiwify, Memberkit, Fluent), o exige prueba de conocimiento — foto, redacción, quiz, documento — antes de aprobar.', fr: 'Émission auto à la fin du cours (Hotmart, Kiwify, Memberkit, Fluent), ou preuve de connaissance requise — photo, dissertation, quiz, document — avant validation.' }, highlight: true },
  { cat: 'integrations', icon: '🔌', title: { pt: 'Hotmart/Memberkit/Kiwify/Eduzz', en: 'Hotmart/Memberkit/Kiwify/Eduzz', es: 'Hotmart/Memberkit/Kiwify/Eduzz', fr: 'Hotmart/Memberkit/Kiwify/Eduzz' }, desc: { pt: 'Webhooks nativos com HMAC. Cert emite automaticamente quando aluno compra.', en: 'Native webhooks with HMAC. Cert auto-issues when student buys.', es: 'Webhooks nativos. Cert auto-emite tras compra.', fr: 'Webhooks natifs. Cert auto-émis après achat.' } },
  { cat: 'integrations', icon: '🎓', title: { pt: 'FluentCommunity (WordPress)', en: 'FluentCommunity (WordPress)', es: 'FluentCommunity (WordPress)', fr: 'FluentCommunity (WordPress)' }, desc: { pt: 'Plugin oficial UniverCert × FluentCommunity. Auto-emit ao completar curso.', en: 'Official plugin. Auto-emit on course completion.', es: 'Plugin oficial. Auto-emit al completar.', fr: 'Plugin officiel. Auto-émission à la fin.' } },
  { cat: 'integrations', icon: '⚡', title: { pt: 'N8N nodes oficial', en: 'Official N8N nodes', es: 'N8N nodes oficial', fr: 'N8N nodes officiel' }, desc: { pt: 'Pacote npm n8n-nodes-univercert. 4 actions: emit, get, list, revoke.', en: 'npm package n8n-nodes-univercert. 4 actions.', es: 'Paquete n8n-nodes-univercert. 4 actions.', fr: 'Package n8n-nodes-univercert. 4 actions.' } },
  { cat: 'integrations', icon: '🚀', title: { pt: 'REST API + bearer auth', en: 'REST API + bearer auth', es: 'REST API + bearer auth', fr: 'API REST + bearer auth' }, desc: { pt: 'API keys com scope read/write/admin. Compatível Zapier, Make, scripts próprios.', en: 'API keys with scope. Zapier/Make compatible.', es: 'API keys con scope. Compatible Zapier/Make.', fr: 'API keys avec scope. Compatible Zapier/Make.' } },
  { cat: 'integrations', icon: '🔁', title: { pt: 'Outgoing webhooks', en: 'Outgoing webhooks', es: 'Outgoing webhooks', fr: 'Webhooks sortants' }, desc: { pt: 'HMAC SHA-256 + retry exponencial. 8 events. Nunca perde delivery.', en: 'HMAC SHA-256 + exponential retry. 8 events. Never miss.', es: 'HMAC SHA-256 + retry. 8 events.', fr: 'HMAC SHA-256 + retry. 8 events.' } },
  { cat: 'integrations', icon: '📘', title: { pt: 'LinkedIn Learning xAPI', en: 'LinkedIn Learning xAPI', es: 'LinkedIn Learning xAPI', fr: 'LinkedIn Learning xAPI' }, desc: { pt: 'Tin Can compatível com Cornerstone, Docebo, Moodle, SAP SuccessFactors.', en: 'Tin Can compatible: Cornerstone, Docebo, Moodle, SAP.', es: 'Compatible Cornerstone, Docebo, Moodle, SAP.', fr: 'Compatible Cornerstone, Docebo, Moodle, SAP.' } },

  // SECURITY
  { cat: 'security', icon: '🔐', title: { pt: 'SSO Google/Microsoft', en: 'SSO Google/Microsoft', es: 'SSO Google/Microsoft', fr: 'SSO Google/Microsoft' }, desc: { pt: 'OAuth nativo Better Auth. SAML via Cloudflare Access (Enterprise).', en: 'Native OAuth. SAML via Cloudflare Access (Enterprise).', es: 'OAuth nativo. SAML (Enterprise).', fr: 'OAuth natif. SAML (Enterprise).' } },
  { cat: 'security', icon: '🛡', title: { pt: '2FA TOTP + backup codes', en: '2FA TOTP + backup codes', es: '2FA TOTP + backup codes', fr: '2FA TOTP + backup codes' }, desc: { pt: 'Google Authenticator, 1Password, Authy. Códigos backup hash SHA-256.', en: 'Google Authenticator, 1Password, Authy. Backup hashed.', es: 'Google Authenticator + códigos backup.', fr: 'Google Authenticator + codes backup.' } },
  { cat: 'security', icon: '🌐', title: { pt: 'IP allowlist', en: 'IP allowlist', es: 'IP allowlist', fr: 'IP allowlist' }, desc: { pt: 'Restringe acesso por CIDR. Separado pra dashboard e API.', en: 'Restrict by CIDR. Separate for dashboard & API.', es: 'Restringir por CIDR.', fr: 'Restreindre par CIDR.' } },
  { cat: 'security', icon: '📋', title: { pt: 'Audit log export', en: 'Audit log export', es: 'Audit log export', fr: 'Export audit log' }, desc: { pt: 'CSV/JSON com range de datas. SOC 2 / LGPD / GDPR ready.', en: 'CSV/JSON. SOC 2 / GDPR ready.', es: 'CSV/JSON. SOC 2 / GDPR.', fr: 'CSV/JSON. SOC 2 / RGPD.' } },
  { cat: 'security', icon: '🔑', title: { pt: 'API keys + rotação', en: 'API keys + rotation', es: 'API keys + rotación', fr: 'API keys + rotation' }, desc: { pt: 'Hash SHA-256, scope, expires_at, request count, last_used. Revogue qualquer hora.', en: 'SHA-256 hashed. Scope, expiry, usage tracking.', es: 'Hash SHA-256. Scope, expiry.', fr: 'Hash SHA-256. Scope, expiry.' } },
  { cat: 'security', icon: '⚡', title: { pt: 'Rate limiting (KV)', en: 'Rate limiting (KV)', es: 'Rate limiting (KV)', fr: 'Rate limiting (KV)' }, desc: { pt: 'Cloudflare KV protege endpoints públicos. Brute-force impossível.', en: 'Cloudflare KV protects public endpoints.', es: 'Cloudflare KV protege endpoints.', fr: 'Cloudflare KV protège endpoints.' } },

  // BUSINESS
  { cat: 'business', icon: '📊', title: { pt: 'Analytics dashboard', en: 'Analytics dashboard', es: 'Analytics dashboard', fr: 'Analytics dashboard' }, desc: { pt: 'Shares por canal, verificações geo, top certs, ranges 7d/30d/90d/365d.', en: 'Shares by channel, geo verifications, top certs.', es: 'Shares por canal, verificaciones geo.', fr: 'Shares par canal, vérifications géo.' } },
  { cat: 'business', icon: '💰', title: { pt: 'Stripe + Pagar.me billing', en: 'Stripe + Pagar.me billing', es: 'Stripe + Pagar.me billing', fr: 'Stripe + Pagar.me billing' }, desc: { pt: '4 planos com trial 14d. PIX BR via Pagar.me, cartão internacional via Stripe.', en: '4 plans, 14d trial. BRL via Pagar.me, USD via Stripe.', es: '4 planes, 14d trial. Multi-moneda.', fr: '4 plans, 14j trial. Multi-devise.' } },
  { cat: 'business', icon: '🤝', title: { pt: 'Affiliate 10% recorrente', en: 'Affiliate 10% recurring', es: 'Afiliados 10% recurrente', fr: 'Affiliés 10% récurrent' }, desc: { pt: 'Indique escolas, ganhe 10% de toda mensalidade. Cookie 60 dias.', en: 'Refer schools, earn 10% recurring. 60-day cookie.', es: 'Refiere, gana 10% recurrente.', fr: 'Référez, gagnez 10% récurrent.' } },
  { cat: 'business', icon: '🌟', title: { pt: 'Educator partner 20%', en: 'Educator partner 20%', es: 'Educator partner 20%', fr: 'Educator partner 20%' }, desc: { pt: 'Programa pra creators com audiência. 20% revenue share.', en: 'Program for creators. 20% revenue share.', es: 'Programa para creators. 20%.', fr: 'Programme créateurs. 20%.' } },
  { cat: 'business', icon: '📦', title: { pt: 'Bulk export PDFs', en: 'Bulk export PDFs', es: 'Bulk export PDFs', fr: 'Export bulk PDFs' }, desc: { pt: 'Selecione até 500 certs, manifest JSON ou CSV. ZIP cliente-side.', en: 'Up to 500 certs, manifest JSON or CSV.', es: 'Hasta 500 certs, manifest JSON o CSV.', fr: 'Jusqu\'à 500 certs, manifest JSON ou CSV.' } },
  { cat: 'business', icon: '⚡', title: { pt: 'Cmd+K search + actions', en: 'Cmd+K search + actions', es: 'Cmd+K búsqueda + acciones', fr: 'Cmd+K recherche + actions' }, desc: { pt: 'Busca global em alunos/certs/templates + 12 slash actions (/emit, /invite).', en: 'Global search + 12 slash actions.', es: 'Búsqueda global + 12 acciones.', fr: 'Recherche globale + 12 actions.' } },
  { cat: 'business', icon: '👥', title: { pt: 'Multi-workspace', en: 'Multi-workspace', es: 'Multi-workspace', fr: 'Multi-workspace' }, desc: { pt: 'Várias escolas numa só conta. Switcher Linear-style.', en: 'Multiple schools, one account. Linear-style switcher.', es: 'Múltiples escuelas, una cuenta.', fr: 'Plusieurs écoles, un compte.' } },
  { cat: 'business', icon: '🔐', title: { pt: 'RBAC 4 níveis', en: 'RBAC 4 levels', es: 'RBAC 4 niveles', fr: 'RBAC 4 niveaux' }, desc: { pt: 'Admin / Editor / Aprovador / Viewer. Invites por email.', en: 'Admin / Editor / Approver / Viewer. Email invites.', es: 'Admin / Editor / Aprobador / Viewer.', fr: 'Admin / Editor / Approbateur / Viewer.' } },
  { cat: 'business', icon: '⏱', title: { pt: 'SSE realtime queue', en: 'SSE realtime queue', es: 'SSE realtime queue', fr: 'SSE queue temps réel' }, desc: { pt: 'Pedidos novos aparecem ao vivo sem F5. Server-Sent Events nativos.', en: 'New requests appear live, no refresh.', es: 'Pedidos en vivo, sin refresh.', fr: 'Demandes en direct, sans refresh.' } },

  // BRANDING
  { cat: 'branding', icon: '🎨', title: { pt: 'White-label total', en: 'Full white-label', es: 'White-label total', fr: 'White-label total' }, desc: { pt: 'Logo, cores, fonte, footer — tudo seu. Sem marca UniverCert no Pro+.', en: 'Logo, colors, fonts, footer — all yours. No UniverCert branding on Pro+.', es: 'Logo, colores, fuente — todo tuyo.', fr: 'Logo, couleurs, footer — tout à vous.' } },
  { cat: 'branding', icon: '🌐', title: { pt: 'Domínio próprio', en: 'Custom domain', es: 'Dominio propio', fr: 'Domaine personnalisé' }, desc: { pt: 'certificados.escola.com aponta pro UniverCert. SSL automático.', en: 'certs.school.com via UniverCert. Auto SSL.', es: 'certs.escola.com con SSL auto.', fr: 'certs.ecole.com avec SSL auto.' } },
  { cat: 'branding', icon: '📧', title: { pt: 'Email sender domain', en: 'Email sender domain', es: 'Email sender domain', fr: 'Email sender domain' }, desc: { pt: 'no-reply@escola.com com DKIM/SPF/DMARC verificados via Resend.', en: 'no-reply@school.com with DKIM/SPF/DMARC.', es: 'no-reply@escola.com con DKIM/SPF.', fr: 'no-reply@ecole.com avec DKIM/SPF.' } },
  { cat: 'branding', icon: '🏫', title: { pt: 'Página /escola/slug', en: 'Issuer page /escola/slug', es: 'Página /escola/slug', fr: 'Page /escola/slug' }, desc: { pt: 'Página pública SEO-friendly com logo, cores, certs recentes, depoimentos.', en: 'Public SEO page with logo, colors, recent certs.', es: 'Página pública SEO con logo.', fr: 'Page publique SEO.' } },
  { cat: 'branding', icon: '🏷', title: { pt: 'Embed badges', en: 'Embed badges', es: 'Embed badges', fr: 'Embed badges' }, desc: { pt: 'Cole SVG no site da escola. 3 variantes (badge, counter, featured) com tracking.', en: 'Paste SVG on school site. 3 variants with tracking.', es: 'Pega SVG. 3 variantes.', fr: 'Collez SVG. 3 variantes.' } },

  // STANDARDS
  { cat: 'standards', icon: '🎖', title: { pt: 'Open Badges 3.0', en: 'Open Badges 3.0', es: 'Open Badges 3.0', fr: 'Open Badges 3.0' }, desc: { pt: '1EdTech standard. Compatível LinkedIn Learning, Credly, Accredible, Badgr.', en: '1EdTech standard. LinkedIn/Credly/Accredible compatible.', es: '1EdTech estándar. Compatible.', fr: '1EdTech standard. Compatible.' } },
  { cat: 'standards', icon: '🔒', title: { pt: 'W3C Verifiable Credentials', en: 'W3C Verifiable Credentials', es: 'W3C Verifiable Credentials', fr: 'W3C Verifiable Credentials' }, desc: { pt: 'VC 2.0 com did:web. Verificável OFFLINE sem chamar nossa API.', en: 'VC 2.0 with did:web. Offline verification.', es: 'VC 2.0 con did:web. Verificación offline.', fr: 'VC 2.0 avec did:web. Vérification hors ligne.' } },
  { cat: 'standards', icon: '✍', title: { pt: 'Ed25519 signing real', en: 'Real Ed25519 signing', es: 'Ed25519 signing real', fr: 'Signature Ed25519 réelle' }, desc: { pt: 'DataIntegrityProof eddsa-rdfc-2022. Wallets W3C verificam sem nossa API.', en: 'DataIntegrityProof eddsa-rdfc-2022.', es: 'DataIntegrityProof eddsa-rdfc-2022.', fr: 'DataIntegrityProof eddsa-rdfc-2022.' } },
  { cat: 'standards', icon: '🪪', title: { pt: 'did:web por workspace', en: 'did:web per workspace', es: 'did:web por workspace', fr: 'did:web par workspace' }, desc: { pt: 'Cada escola tem DID próprio: did:web:univercert.net:escola:slug. Resolver W3C.', en: 'Each school has its own DID. W3C resolver.', es: 'Cada escuela con DID propio.', fr: 'Chaque école avec DID propre.' } },
  { cat: 'standards', icon: '📡', title: { pt: 'xAPI Tin Can statements', en: 'xAPI Tin Can statements', es: 'xAPI Tin Can statements', fr: 'xAPI Tin Can statements' }, desc: { pt: 'Padrão ADL 1.0.3. Import em qualquer LRS do mercado.', en: 'ADL 1.0.3 standard. Import in any LRS.', es: 'Estándar ADL. Cualquier LRS.', fr: 'Standard ADL. Tout LRS.' } },
  { cat: 'standards', icon: '🔍', title: { pt: 'Verifier público SEO', en: 'Public SEO verifier', es: 'Verifier público SEO', fr: 'Vérificateur public SEO' }, desc: { pt: '/verificar com hash/ID/URL. Indexado no Google. Sem login.', en: '/verify with hash/ID/URL. Google indexed.', es: '/verificar indexado Google.', fr: '/verifier indexé Google.' } },
];

// COMPARISON TABLE — vs competidores
export type CompareRow = { feature: ML; uc: string; credly: string; accredible: string; sertifier: string; hotmart: string };

export const COMPARISON: CompareRow[] = [
  { feature: { pt: 'Preço inicial mensal', en: 'Starting monthly price', es: 'Precio inicial mensual', fr: 'Prix initial mensuel' }, uc: 'R$ 97', credly: '$249', accredible: '$295', sertifier: '$199', hotmart: 'Pago por cert' },
  { feature: { pt: 'Plano free real', en: 'Real free plan', es: 'Plan free real', fr: 'Plan free réel' }, uc: '✅ 50/mês', credly: '❌', accredible: '❌ trial', sertifier: '❌ trial', hotmart: '❌' },
  { feature: { pt: 'PIX brasileiro', en: 'Brazilian PIX', es: 'PIX brasileño', fr: 'PIX brésilien' }, uc: '✅', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '✅' },
  { feature: { pt: 'Suporte em português', en: 'Portuguese support', es: 'Soporte en portugués', fr: 'Support en portugais' }, uc: '✅ nativo', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '✅' },
  { feature: { pt: 'Editor drag-and-drop', en: 'Drag-and-drop editor', es: 'Editor drag-and-drop', fr: 'Éditeur drag-and-drop' }, uc: '✅ GODMODE', credly: '⚠ básico', accredible: '✅', sertifier: '✅', hotmart: '⚠ limitado' },
  { feature: { pt: 'IA gera template', en: 'AI generates template', es: 'IA genera template', fr: 'IA génère template' }, uc: '✅ Claude Haiku', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '❌' },
  { feature: { pt: 'OCR de RG/CNH', en: 'ID OCR', es: 'OCR cédula', fr: 'OCR pièce d\'identité' }, uc: '✅ Claude vision', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '❌' },
  { feature: { pt: 'Face match anti-fraude', en: 'Face match anti-fraud', es: 'Face match anti-fraude', fr: 'Face match anti-fraude' }, uc: '✅ exclusivo', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '❌' },
  { feature: { pt: 'Apple Wallet', en: 'Apple Wallet', es: 'Apple Wallet', fr: 'Apple Wallet' }, uc: '✅ pkpass real', credly: '✅', accredible: '✅', sertifier: '⚠', hotmart: '❌' },
  { feature: { pt: 'Google Wallet', en: 'Google Wallet', es: 'Google Wallet', fr: 'Google Wallet' }, uc: '✅ JWT real', credly: '✅', accredible: '⚠', sertifier: '⚠', hotmart: '❌' },
  { feature: { pt: 'LinkedIn Add-to-Profile', en: 'LinkedIn Add-to-Profile', es: 'LinkedIn Add-to-Profile', fr: 'LinkedIn Add-to-Profile' }, uc: '✅', credly: '✅', accredible: '✅', sertifier: '✅', hotmart: '⚠ link só' },
  { feature: { pt: 'Open Badges 3.0', en: 'Open Badges 3.0', es: 'Open Badges 3.0', fr: 'Open Badges 3.0' }, uc: '✅ Ed25519 real', credly: '✅ 2.0', accredible: '✅ 3.0', sertifier: '✅', hotmart: '❌' },
  { feature: { pt: 'W3C Verifiable Credentials', en: 'W3C VC', es: 'W3C VC', fr: 'W3C VC' }, uc: '✅ did:web', credly: '⚠ alpha', accredible: '⚠', sertifier: '❌', hotmart: '❌' },
  { feature: { pt: 'Webhooks com HMAC', en: 'Webhooks with HMAC', es: 'Webhooks HMAC', fr: 'Webhooks HMAC' }, uc: '✅ + retry', credly: '✅', accredible: '✅', sertifier: '⚠', hotmart: '❌' },
  { feature: { pt: 'API REST + bearer', en: 'REST API + bearer', es: 'API REST + bearer', fr: 'API REST + bearer' }, uc: '✅ unlimited', credly: '✅ enterprise', accredible: '✅', sertifier: '✅', hotmart: '⚠ limitado' },
  { feature: { pt: 'N8N nodes oficial', en: 'Official N8N nodes', es: 'N8N nodes oficial', fr: 'N8N nodes officiel' }, uc: '✅ exclusivo', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '❌' },
  { feature: { pt: 'Hotmart/Memberkit/Kiwify', en: 'Hotmart/Memberkit/Kiwify', es: 'Hotmart/Memberkit/Kiwify', fr: 'Hotmart/Memberkit/Kiwify' }, uc: '✅ nativo', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '✅ self' },
  { feature: { pt: 'WordPress FluentCommunity', en: 'WordPress FluentCommunity', es: 'WordPress FluentCommunity', fr: 'WordPress FluentCommunity' }, uc: '✅ plugin', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '❌' },
  { feature: { pt: 'SSO Google/Microsoft', en: 'SSO Google/Microsoft', es: 'SSO Google/Microsoft', fr: 'SSO Google/Microsoft' }, uc: '✅ free', credly: '⚠ enterprise', accredible: '⚠ enterprise', sertifier: '⚠ pro', hotmart: '❌' },
  { feature: { pt: 'White-label completo', en: 'Full white-label', es: 'White-label completo', fr: 'White-label complet' }, uc: '✅ Pro R$297', credly: '⚠ $1000+', accredible: '⚠ $500+', sertifier: '⚠ $300+', hotmart: '❌' },
  { feature: { pt: 'Custom domain SSL', en: 'Custom domain SSL', es: 'Custom domain SSL', fr: 'Custom domain SSL' }, uc: '✅ auto', credly: '⚠ enterprise', accredible: '⚠ enterprise', sertifier: '⚠', hotmart: '❌' },
  { feature: { pt: 'Audit log export', en: 'Audit log export', es: 'Audit log export', fr: 'Export audit log' }, uc: '✅ CSV/JSON', credly: '⚠', accredible: '⚠ enterprise', sertifier: '❌', hotmart: '❌' },
  { feature: { pt: 'Marketplace templates', en: 'Templates marketplace', es: 'Marketplace templates', fr: 'Marketplace templates' }, uc: '✅', credly: '❌', accredible: '❌', sertifier: '⚠', hotmart: '❌' },
  { feature: { pt: 'Affiliate program', en: 'Affiliate program', es: 'Programa de afiliados', fr: 'Programme d\'affiliés' }, uc: '✅ 10%-20%', credly: '❌', accredible: '❌', sertifier: '❌', hotmart: '❌' },
  { feature: { pt: 'Bulk emission CSV', en: 'Bulk CSV emission', es: 'Emisión bulk CSV', fr: 'Émission bulk CSV' }, uc: '✅ ilimitado', credly: '✅', accredible: '✅', sertifier: '✅', hotmart: '⚠' },
  { feature: { pt: 'PWA mobile-first', en: 'PWA mobile-first', es: 'PWA mobile-first', fr: 'PWA mobile-first' }, uc: '✅', credly: '⚠', accredible: '⚠', sertifier: '⚠', hotmart: '❌' },
  { feature: { pt: 'Verificador SEO público', en: 'Public SEO verifier', es: 'Verificador SEO público', fr: 'Vérificateur SEO public' }, uc: '✅', credly: '✅', accredible: '✅', sertifier: '✅', hotmart: '⚠' },
  { feature: { pt: 'Cobrança em BRL', en: 'BRL billing', es: 'Cobro en BRL', fr: 'Facturation BRL' }, uc: '✅ NF-e', credly: '❌ USD only', accredible: '❌ USD', sertifier: '❌ USD', hotmart: '✅' },
];

export function getCategoryLabel(cat: string, locale: Locale): string {
  const labels: Record<string, ML> = {
    editor: { pt: 'Editor profissional', en: 'Pro editor', es: 'Editor profesional', fr: 'Éditeur pro' },
    ai: { pt: 'Inteligência artificial', en: 'Artificial intelligence', es: 'Inteligencia artificial', fr: 'Intelligence artificielle' },
    delivery: { pt: 'Entrega & engajamento', en: 'Delivery & engagement', es: 'Entrega y engagement', fr: 'Livraison & engagement' },
    integrations: { pt: 'Integrações', en: 'Integrations', es: 'Integraciones', fr: 'Intégrations' },
    security: { pt: 'Segurança & compliance', en: 'Security & compliance', es: 'Seguridad', fr: 'Sécurité' },
    business: { pt: 'Negócio & analytics', en: 'Business & analytics', es: 'Negocio', fr: 'Business' },
    branding: { pt: 'Marca & white-label', en: 'Brand & white-label', es: 'Marca', fr: 'Marque' },
    standards: { pt: 'Padrões internacionais', en: 'International standards', es: 'Estándares', fr: 'Standards' },
  };
  return labels[cat]?.[locale] ?? labels[cat]?.pt ?? cat;
}

export function pickML(ml: ML, locale: Locale): string {
  return ml[locale] ?? ml.pt;
}
